version: "2.4"
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U posgres" ]
      interval: 50s
      timeout: 5s
      retries: 2

  demo:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy